Repository diabeatz96/cain, pull requests merged in 2024-08, with the labels that each got.

#4 Changes to actor to small fixes for roll output.
  module/documents/actor.mjs
  module/sheets/actor-sheet.mjs
Labels: bug

#18 Added in option to allow players to see overview
  module/cain.mjs
  system.json
Labels: enhancement

#15 -…
  module/cain.mjs
  module/data/actor-character.mjs
  module/sheets/actor-sheet.mjs
  system.json
  templates/actor/parts/actor-features.hbs
Labels: enhancement

#25 Adjusted and added in necessary changes for severe attack
  css/cain.css
  module/data/actor-npc.mjs
  module/sheets/actor-sheet.mjs
  system.json
  templates/actor/npc-parts/actor-attacks.hbs
  templates/actor/npc-parts/actor-description.hbs
Labels: enhancement

#26 Fixed small bug where mundane NPC's sheet wouldn't open
  module/sheets/actor-sheet.mjs
  system.json
Labels: enhancement

#29 Finalized features in rework
  module/data/blasphemy/item-blasphemy.mjs
  module/documents/homebrew-window.mjs
  module/documents/player-overview.mjs
  module/sheets/actor-sheet.mjs
  packs/agenda2/000004.log
  packs/agenda2/000025.log
  packs/agenda2/CURRENT
  packs/agenda2/LOG
  packs/agenda2/LOG.old
  packs/agenda2/MANIFEST-000002
  packs/agenda2/MANIFEST-000024
  packs/blasphemy2/000004.log
  packs/blasphemy2/000021.ldb
  packs/blasphemy2/000025.ldb
  packs/blasphemy2/000026.log
  packs/blasphemy2/CURRENT
  packs/blasphemy2/LOG
  packs/blasphemy2/LOG.old
  packs/blasphemy2/MANIFEST-000002
  packs/blasphemy2/MANIFEST-000024
  templates/actor/parts/actor-abilities.hbs
  templates/homebrew-window.hbs
  templates/item/item-blasphemy-sheet.hbs
  templates/item/item-blasphemyPower-sheet.hbs
  templates/item/parts/item-blasphemy-power-sheet.hbs
  templates/player-overview/skills.hbs
Labels: enhancement

#31 Switched power items to classes instead of ids since there can be multiple (one add power box per blasphemy)
  module/sheets/actor-sheet.mjs
  templates/actor/parts/actor-abilities.hbs
Labels: enhancement

#32 A couple more bugfixes with homebrew and enabling formatting on items
  module/cain.mjs
  module/documents/homebrew-window.mjs
  templates/item/item-blasphemyPower-sheet.hbs
  templates/item/parts/item-blasphemy-power-sheet.hbs
Labels: bug, enhancement

#36 Added in one change to value.
  module/data/actor-character.mjs
  system.json
Labels: enhancement
