Repository diabeatz96/cain, pull requests merged in 2024-09, with the labels that each got.

#39 Aesthetic updates
  css/cain.css
  module/cain.mjs
  module/data/agenda/item-agenda.mjs
  module/data/base-item.mjs
  module/data/blasphemy/item-blasphemy.mjs
  module/sheets/actor-sheet.mjs
  module/sheets/item-sheet.mjs
  packs/agenda/000067.log
  packs/agenda/LOG.old
  packs/agenda/MANIFEST-000066
  packs/agenda2/000038.log
  packs/agenda2/CURRENT
  packs/agenda2/LOG.old
  packs/agenda2/MANIFEST-000037
  packs/blasphemy/000067.log
  packs/blasphemy/CURRENT
  packs/blasphemy/LOG.old
  packs/blasphemy/MANIFEST-000066
  packs/blasphemy2/000039.log
  packs/blasphemy2/CURRENT
  packs/blasphemy2/LOG
  packs/blasphemy2/LOG.old
  packs/blasphemy2/MANIFEST-000038
  packs/items/000068.log
  packs/items/CURRENT
  packs/items/LOG.old
  packs/items/MANIFEST-000067
  packs/tables/000067.log
  packs/tables/LOG
  packs/tables/LOG.old
  packs/tables/MANIFEST-000066
  templates/actor/actor-character-sheet.hbs
  templates/actor/parts/actor-abilities.hbs
  templates/actor/parts/actor-features.hbs
  templates/item/item-blasphemy-sheet.hbs
  templates/item/item-blasphemyPower-sheet.hbs
  templates/item/parts/item-blasphemy-power-partial.hbs
  templates/item/parts/item-blasphemy-power-sheet.hbs
Labels: enhancement

#41 Added in several small fixes to address
  module/sheets/item-sheet.mjs
  templates/actor/parts/actor-abilities.hbs
  templates/item/item-blasphemy-sheet.hbs
Labels: bug

#43 Removed height on blasphemy powers
  templates/item/item-blasphemy-sheet.hbs
  templates/item/parts/item-blasphemy-power-sheet.hbs
Labels: bug

#44 Change kit and sin adjustment UI
  assets/sheet/CAIN-eye-0-0.png
  assets/sheet/CAIN-eye-0-1.png
  assets/sheet/CAIN-eye-1-0.png
  assets/sheet/CAIN-eye-1-1.png
  assets/sheet/CAIN-eye-2-0.png
  assets/sheet/CAIN-eye-2-1.png
  assets/sheet/CAIN-eye-3-0.png
  assets/sheet/CAIN-eye-3-1.png
  assets/sheet/CAIN-eye-4-0.png
  assets/sheet/CAIN-eye-4-1.png
  assets/sheet/CAIN-eye-5-0.png
  assets/sheet/CAIN-eye-5-1.png
  assets/sheet/CAIN-eye-6-0.png
  assets/sheet/CAIN-eye-6-1.png
  assets/sheet/CAIN-eye-closed.png
  assets/sheet/CAIN-eye-old.png
  assets/sheet/CAIN-eye-small-0.png
  assets/sheet/CAIN-eye-small-1.png
  assets/sheet/CAIN-eye-small-2.png
  assets/sheet/CAIN-eye-small-3.png
  assets/sheet/CAIN-eye-small-4.png
  assets/sheet/CAIN-eye-small-5.png
  assets/sheet/CAIN-eye-small-6.png
  assets/sheet/CAIN-eye-small-closed.png
  assets/sheet/CAIN-sin-no.png
  css/cain.css
  css/eye-anim.css
  lang/en.json
  module/cain.mjs
  module/sheets/actor-sheet.mjs
  templates/actor/parts/actor-features.hbs
  templates/actor/parts/actor-sin.hbs
Labels: enhancement

#45 Sin mark update backend
  lang/en.json
  module/cain.mjs
  module/data/_module.mjs
  module/data/sins/item-sin-mark-ability.mjs
  module/data/sins/item-sin-mark.mjs
  module/helpers/templates.mjs
  module/sheets/item-sheet.mjs
  template.json
  templates/item/item-sinMark-sheet.hbs
  templates/item/item-sinMarkAbility-sheet.hbs
  templates/item/parts/item-sin-mark-partial.hbs
Labels: enhancement

#51 Added Max XP buttons
  module/sheets/actor-sheet.mjs
  templates/actor/parts/actor-features.hbs
Labels: enhancement

#55 Update README.md
  README.md
Labels: documentation

#61 small fix with empty kit sprite
  assets/KIT/KIT-empty.png
  assets/player_ID.png
  templates/actor/actor-character-sheet.hbs
Labels: bug

#63 fixed incomplete header merge
  assets/player_ID.png
  system.json
  templates/actor/actor-character-sheet.hbs
Labels: bug

#65 Accessibility Patch In
  assets/UI_Normal.png
  assets/UI_Plain.png
  assets/generic_exo.png
  assets/generic_sin.png
  assets/homebrew.png
  css/accessibility.css
  css/cain.css
  module/cain.mjs
  module/data/actor-character.mjs
  module/data/actor-npc.mjs
  system.json
  templates/actor/actor-character-sheet.hbs
  templates/actor/actor-mundane-sheet.hbs
  templates/actor/actor-npc-sheet.hbs
  templates/actor/parts/actor-abilities.hbs
  templates/actor/parts/actor-features.hbs
Labels: enhancement

#70 Tutorial first load
  assets/Tutorial/doc_ids.png
  module/cain.mjs
  system.json
Labels: documentation, enhancement

#75 Fix afflictions not showing correctly and add kit point min/max
  module/documents/player-overview.mjs
  module/sheets/actor-sheet.mjs
  system.json
  templates/actor/actor-character-sheet.hbs
  templates/actor/parts/actor-abilities.hbs
  templates/actor/parts/actor-items.hbs
  templates/player-overview/overview.hbs
Labels: bug, enhancement

#77 Refactor NPC schema to include traumas as an array field with questions and answers
  module/data/actor-npc.mjs
  module/sheets/actor-sheet.mjs
  templates/actor/actor-npc-sheet.hbs
  templates/actor/npc-parts/actor-description.hbs
  templates/actor/npc-parts/actor-palace-pressure.hbs
Labels: enhancement
